services:
  php-apache:
    ports:
      - "80:80"
    build: './build/php'
    volumes:
      - ./media:/var/www/html/media
      - ./src:/var/www/html
  mysql:
    ports:
      - "3306:3306"
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "n01415150"
      MYSQL_DATABASE: "myousik"
    volumes:
      - dbData:/var/lib/mysql
volumes:
  dbData:
